apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5cl0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5cl0
    app.kubernetes.io/part-of: hacbs-test-project
  name: hacbs-test-project-5cl0
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5cl0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5cl0
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ktsao-tenant/hacbs-test-project/hacbs-test-project-5cl0@sha256:8d4e7998715bf272b0a6f01a8680a0b05c58d9bce4bcd5d94148f4d3dbae1833
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
